name: Find actual patch branch

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write
  issues: write
  actions: write

jobs:
  show-squash-commit:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.issue.pull_request != null &&
       startsWith(github.event.comment.body, 'deploy'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find actual patch branch
        id: patch
        run: |
          BRANCHES=$(git ls-remote --heads origin "patch/v*" | awk '{print $2}' | sed 's|refs/heads/||')
          echo "Found branches:"
          echo "$BRANCHES"

          LATEST=$(echo "$BRANCHES" | sort -t'v' -k2 -V | tail -n 1)
          echo "Latest patch branch: $LATEST"
          echo "latest_patch_branch=$LATEST" >> $GITHUB_OUTPUT
